#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const name = process.argv[2];

if (!name) {
  console.log('name is required');
  process.exit();
}

const dir = path.join(process.cwd(), 'components', name);

try {
  fs.statSync(dir);
  console.log('package already exists');
  process.exit();
} catch (error) {
  console.log(`creating component ${name}`);
}

fs.mkdirSync(dir);

fs.writeFileSync(path.join(dir, 'package.json'),
`{
  "name": "${name}",
  "version": "0.0.0",
  "private": true,
  "main": "component.js",
  "dependencies": {
    "th-core": "*"
  }
}
`);

fs.writeFileSync(path.join(dir, 'component.js'),
`const core = require('th-core');

class Component extends core(HTMLElement) {
  constructor() {
    super({
      template: '${name}',
    });
  }
}

const template = require('./template.html');
document.head.insertAdjacentHTML('beforeend', template);

window.customElements.define('${name}', Component);
`);

fs.writeFileSync(path.join(dir, 'template.html'),
`<style>
  ${name} {
    display: flex;
  }
</style>

<template id="${name}">
  ${name}
</template>
`);

console.log('complete');
